### PR TITLE
feat: CRUD operations for Accounts

### LINKED ISSUE #1: [4.1.1] Admin/Normal User (Accounts) - C: Add new user account
POST /api/users

### LINKED ISSUE #6: [4.1.5.1] Admin (Accounts) - R: Query all user accounts
GET /api/users

### LINKED ISSUE #7: [4.1.5.2] Admin (Accounts) - D: Delete user accounts
DELETE /api/users/{id}

### LINKED ISSUE #8: [4.1.5.3] Admin (Accounts) - U: Modify user accounts
PUT /api/users/{id}

### PR DESCRIPTION
**Pull request by isabellepakyishan**
POST TSAO Account: Closes #1 

GET TSAO Account: Closes #6 
- Retrieve all accounts
- Retrieve single account

PATCH TSAO Account: Closes #8 
- Modify account information
- Modify password
- Approve account

DELETE TSAO Account: Closes #7

### CODE REVIEW

**Review by Kuan-Zher — APPROVED** [review]
Looks good

**Review by jiachenyee — CHANGES_REQUESTED** [review]
not sure if i know enough about Go but should the Account struct be a separate file?

**Comment by Kuan-Zher** [comment]
> not sure if i know enough about Go but should the Account struct be a separate file?

like class files in C#?

**Comment by isabellepakyishan** [comment]
> not sure if i know enough about Go but should the Account struct be a separate file?

That is what we were taught to do in ETI though, ask Mr Wesley HAHA

**Comment by isabellepakyishan** [comment]
have made the necessary adjustments and changes, please refer to the 2 PRs created

refactor: Records microservice - https://github.com/DevOps-2023-TeamA/tsao-backend-svc/pull/16
refactor: Auth microservice - https://github.com/DevOps-2023-TeamA/tsao-backend-svc/pull/17

@Kuan-Zher  @jiachenyee

**Review by jiachenyee — APPROVED** [review]
lgtm

**Pull request merged**
